export const GUIDE_DESTINATIONS = new Set([
  '/',
  '/musicians',
  '/gigs',
  '/venues',
  '/bands',
  '/community',
  '/signup',
  '/signup?next=%2Fmusicians&role=musician',
  '/signup?next=%2Fgigs&role=organizer',
  '/signup?next=%2Fgigs&role=musician',
  '/login',
]);

export const GUIDE_FALLBACK = Object.freeze({
  kind: 'fallback',
  intentId: null,
  confidence: 0,
  answer: "I don't know that one yet, but I can help you find your way around iConnect.",
  action: { label: 'Start at the homepage', path: '/' },
  suggestions: ['Find a gig', 'Find a musician', 'How does iConnect work?'],
});

export const GUIDE_INTENTS = Object.freeze([
  {
    id: 'about-iconnect',
    phrases: ['what is iconnect', 'how does iconnect work', 'what do you do'],
    keywords: ['iconnect', 'marketplace', 'network', 'platform'],
    answer: 'iConnect connects musicians, organizers, venues, and live-music opportunities in one public network.',
    action: { label: 'Explore iConnect', path: '/' },
    suggestions: ['Find a gig', 'Find a musician'],
    contextPaths: ['/'],
  },
  {
    id: 'find-gig',
    phrases: ['find a gig', 'find gigs', 'open gig', 'gig opportunities', 'apply to a gig', 'gigs near me'],
    keywords: ['gig', 'opportunity', 'apply', 'musician work'],
    answer: 'Browse open gigs by format, location, genre, and the details that help you decide whether the opportunity fits.',
    action: { label: 'Browse gigs', path: '/gigs' },
    suggestions: ['How do I apply?', 'Create a musician profile'],
    contextPaths: ['/gigs', '/musicians'],
  },
  {
    id: 'find-musician',
    phrases: ['find a musician', 'find musicians', 'book a singer', 'book a musician', 'hire a band', 'find talent', 'find a performer'],
    keywords: ['musician', 'singer', 'performer', 'talent', 'band', 'book'],
    answer: 'Browse musician profiles and EPKs to find people whose sound, location, and experience fit your event.',
    action: { label: 'Browse musicians', path: '/musicians' },
    suggestions: ['How do I post a gig?', 'Browse venues'],
    contextPaths: ['/musicians', '/venues'],
  },
  {
    id: 'browse-venues',
    phrases: ['browse venues', 'find a venue', 'find venues', 'where is the music happening'],
    keywords: ['venue', 'room', 'space', 'event'],
    answer: 'Explore venues, capacities, locations, and the gigs already connected to each room.',
    action: { label: 'Browse venues', path: '/venues' },
    suggestions: ['Find a gig', 'Find musicians'],
    contextPaths: ['/venues'],
  },
  {
    id: 'browse-community',
    phrases: ['browse community', 'see the community', 'find collaborators', 'meet musicians', 'community feed'],
    keywords: ['community', 'collaborate', 'collaboration', 'people'],
    answer: 'The community feed is where musicians and bands share updates, recruitment calls, and collaboration opportunities.',
    action: { label: 'Open community', path: '/community' },
    suggestions: ['Browse bands', 'Create a profile'],
    contextPaths: ['/community'],
  },
  {
    id: 'browse-bands',
    phrases: ['browse bands', 'find a band', 'find bands', 'join a band', 'band collectives'],
    keywords: ['band', 'collective', 'members', 'join'],
    answer: 'Browse bands and collectives by name, genre, and location, then open a band page to see its members and updates.',
    action: { label: 'Browse bands', path: '/bands' },
    suggestions: ['Open community', 'Create a band'],
    contextPaths: ['/bands'],
  },
  {
    id: 'create-profile',
    phrases: ['create a profile', 'build a profile', 'make a musician profile', 'join as a musician'],
    keywords: ['profile', 'join', 'musician', 'epk'],
    answer: 'Create a musician profile to share your sound, instruments, location, availability, and EPK with organizers.',
    action: { label: 'Create a musician profile', path: '/signup?next=%2Fmusicians&role=musician' },
    suggestions: ['Find a gig', 'What is an EPK?'],
    contextPaths: ['/musicians', '/epk'],
  },
  {
    id: 'post-gig',
    phrases: ['post a gig', 'create a gig', 'list an opportunity', 'book talent for an event'],
    keywords: ['post', 'gig', 'organizer', 'event', 'opportunity'],
    answer: 'Organizers can join iConnect and use their dashboard to publish a clear gig brief for musicians to discover.',
    action: { label: 'Join as an organizer', path: '/signup?next=%2Fgigs&role=organizer' },
    suggestions: ['Find a musician', 'Browse venues'],
    contextPaths: ['/gigs', '/venues'],
  },
  {
    id: 'view-epk',
    phrases: ['what is an epk', 'view an epk', 'open an epk', 'electronic press kit', 'media kit'],
    keywords: ['epk', 'press', 'media', 'kit'],
    answer: 'An EPK is a musician’s shareable press kit with their headline, sound, instruments, demos, links, and booking details.',
    action: { label: 'Browse musician profiles', path: '/musicians' },
    suggestions: ['Create a musician profile', 'Find a musician'],
    contextPaths: ['/musicians', '/epk'],
  },
  {
    id: 'apply-to-gig',
    phrases: ['how do i apply', 'apply for a gig', 'send an application', 'apply to this gig'],
    keywords: ['apply', 'application', 'gig', 'pitch'],
    answer: 'Open a gig detail page to review the brief, then join as a musician to send an application to the organizer.',
    action: { label: 'Browse open gigs', path: '/gigs' },
    suggestions: ['Create a musician profile', 'Find a gig'],
    contextPaths: ['/gigs'],
  },
  {
    id: 'signup',
    phrases: ['how do i sign up', 'create an account', 'join iconnect', 'register'],
    keywords: ['signup', 'account', 'register', 'join'],
    answer: 'You can browse public listings first, then create a free musician or organizer account when you are ready to take the next step.',
    action: { label: 'Create a free account', path: '/signup' },
    suggestions: ['Find a gig', 'Find a musician'],
    contextPaths: ['/signup'],
  },
  {
    id: 'login',
    phrases: ['how do i log in', 'sign in', 'log in', 'login'],
    keywords: ['login', 'sign in', 'account'],
    answer: 'Use your iConnect account details to return to your dashboard and continue where you left off.',
    action: { label: 'Log in', path: '/login' },
    suggestions: ['Create an account', 'Find a gig'],
    contextPaths: ['/login'],
  },
]);
