import bcrypt from 'bcryptjs';

const HASH_ROUNDS = 10;

const demoPassword = 'password123';

const hash = (value) => bcrypt.hashSync(value, HASH_ROUNDS);

export function seedData() {
  const now = Date.now();
  const iso = (daysFromNow) => new Date(now + daysFromNow * 86400000).toISOString();

  const users = [
    {
      id: 'u_ayo',
      role: 'musician',
      name: 'Ayo Adeyemi',
      email: 'ayo@example.com',
      passwordHash: hash(demoPassword),
      title: 'Saxophonist · Session & Live',
      bio: 'Alto and tenor sax player blending highlife, Afrobeat and contemporary jazz. Available for festivals, studio sessions and private events across Lagos and beyond.',
      location: 'Lagos, Nigeria',
      genre: 'Jazz / Afrobeat',
      instruments: ['Saxophone', 'Flute'],
      yearsExperience: 9,
      rate: { currency: 'NGN', amount: 120000, unit: 'per gig' },
      availability: 'open',
      tags: ['Jazz', 'Highlife', 'Studio sessions', 'Festival', 'Live band'],
      createdAt: iso(-180),
    },
    {
      id: 'u_grace',
      role: 'musician',
      name: 'Grace Eze',
      email: 'grace@example.com',
      passwordHash: hash(demoPassword),
      title: 'Vocalist · Afrobeat & Soul',
      bio: 'Lead vocalist with a warm, dynamic range. Comfortable with Afrobeat, Soul, Gospel RnB, and can front a band or join a session as a featured vocalist.',
      location: 'Lagos, Nigeria',
      genre: 'Afrobeat / Soul',
      instruments: ['Vocals'],
      yearsExperience: 6,
      rate: { currency: 'NGN', amount: 90000, unit: 'per gig' },
      availability: 'open',
      tags: ['Vocals', 'Afrobeat', 'Soul', 'Gospel', 'Featured artist'],
      createdAt: iso(-150),
    },
    {
      id: 'u_tunde',
      role: 'musician',
      name: 'Tunde Bakare',
      email: 'tunde@example.com',
      passwordHash: hash(demoPassword),
      title: 'Guitarist · Highlife & Gospel',
      bio: 'Acoustic and electric guitarist rooted in Nigerian highlife. Leads a 4-piece band and takes on wedding, church and event bookings nationwide.',
      location: 'Abuja, Nigeria',
      genre: 'Highlife / Gospel',
      instruments: ['Guitar', 'Band leader'],
      yearsExperience: 12,
      rate: { currency: 'NGN', amount: 150000, unit: 'per gig' },
      availability: 'open',
      tags: ['Highlife', 'Gospel', 'Weddings', 'Band leader', 'Acoustic'],
      createdAt: iso(-120),
    },
    {
      id: 'u_nia',
      role: 'musician',
      name: 'Nia Olawale',
      email: 'nia@example.com',
      passwordHash: hash(demoPassword),
      title: 'Singer-songwriter · Acoustic',
      bio: 'Independent singer-songwriter performing original Afro-fusion and acoustic sets. Great for intimate shows, brunch concerts and opening slots.',
      location: 'Lagos, Nigeria',
      genre: 'Indie / Afro-fusion',
      instruments: ['Vocals', 'Piano', 'Acoustic guitar'],
      yearsExperience: 4,
      rate: { currency: 'NGN', amount: 60000, unit: 'per gig' },
      availability: 'open',
      tags: ['Singer-songwriter', 'Acoustic', 'Brunch', 'Opening act', 'Original music'],
      createdAt: iso(-90),
    },
    {
      id: 'u_chidi',
      role: 'organizer',
      name: 'Chidi Umeh',
      email: 'chidi@example.com',
      passwordHash: hash(demoPassword),
      title: 'The Jazz House',
      bio: 'Independent Lagos live-music venue hosting jazz, soul and Afrobeat nights every month. We book quality acts for our stage and private events.',
      location: 'Lagos, Nigeria',
      genre: 'Jazz / Soul',
      roleLabel: 'Venue organizer',
      createdAt: iso(-160),
    },
    {
      id: 'u_amara',
      role: 'organizer',
      name: 'Amara Kalu',
      email: 'amara@example.com',
      passwordHash: hash(demoPassword),
      title: 'PalmWaves Festival',
      bio: 'Music and arts festival brand producing outdoor concerts, brand activations and corporate showcases across West Africa.',
      location: 'Lagos, Nigeria',
      genre: 'Festivals / Concerts',
      roleLabel: 'Festival producer',
      createdAt: iso(-140),
    },
    {
      id: 'u_femi',
      role: 'organizer',
      name: 'Femi Okoro',
      email: 'femi@example.com',
      passwordHash: hash(demoPassword),
      title: 'Lagos Civic Hall',
      bio: 'Multi-purpose event and concert hall hosting corporate galas, end-of-year parties and community concerts.',
      location: 'Lagos, Nigeria',
      genre: 'Corporate / Events',
      roleLabel: 'Event hall',
      createdAt: iso(-100),
    },
    {
      id: 'u_admin',
      role: 'admin',
      name: 'iConnect Admin',
      email: 'admin@example.com',
      passwordHash: hash(demoPassword),
      title: 'Platform admin',
      bio: 'Administrator responsible for keeping iConnect safe and trustworthy.',
      location: 'Lagos, Nigeria',
      genre: '',
      roleLabel: 'Admin',
      createdAt: iso(-60),
    },
  ];

  const gigs = [
    {
      id: 'g_sunset_jazz',
      title: 'Sunset Jazz Night',
      description: 'The Jazz House hosts its monthly Sunset Jazz Night. We are booking 1 featured saxophonist and a 2-piece rhythm section for an intimate, seated concert. The set is 75 minutes with a 20 minute break.',
      type: 'Club / Pub',
      venue: 'The Jazz House',
      location: 'Lagos, Nigeria',
      date: iso(24),
      startTime: '19:00',
      endTime: '22:30',
      fee: { currency: 'NGN', amount: 120000 },
      capacity: 2,
      status: 'open',
      genre: 'Jazz / Soul',
      tags: ['Live band', 'Featured artist', 'Jazz', 'Night show'],
      requirements: 'Own instrument, stage-ready, reliable performer. Repertoire for a seated jazz audience preferred.',
      hostId: 'u_chidi',
      hostName: 'Chidi Umeh · The Jazz House',
      createdAt: iso(-10),
      updatedAt: iso(-10),
    },
    {
      id: 'g_palmwaves',
      title: 'Afrobeat + Highlife Festival Stage',
      description: 'PalmWaves Festival is curating a new Afrobeat & Highlife stage. We need versatile musicians and bands for a full-day outdoor festival. Solo performers and acts with backing bands are welcome to apply.',
      type: 'Festival',
      venue: 'PalmWaves Festival Grounds',
      location: 'Lagos, Nigeria',
      date: iso(38),
      startTime: '12:00',
      endTime: '21:00',
      fee: { currency: 'NGN', amount: 350000 },
      capacity: 6,
      status: 'open',
      genre: 'Afrobeat / Highlife',
      tags: ['Festival', 'Outdoor', 'Band booking', 'Featured set'],
      requirements: 'Submit a short 2min clip or EPK. Must handle a large outdoor stage and festival crowd.',
      hostId: 'u_amara',
      hostName: 'Amara Kalu · PalmWaves Festival',
      createdAt: iso(-8),
      updatedAt: iso(-8),
    },
    {
      id: 'g_year_end_gala',
      title: 'Corporate End-of-Year Concert',
      description: 'Lagos Civic Hall is hosting a company end-of-year gala. We need a soul/RnB vocalist and an acoustic guitarist for a 60-minute entertainment set plus 30 minutes of background music.',
      type: 'Corporate',
      venue: 'Lagos Civic Hall',
      location: 'Lagos, Nigeria',
      date: iso(58),
      startTime: '18:30',
      endTime: '22:00',
      fee: { currency: 'NGN', amount: 180000 },
      capacity: 2,
      status: 'open',
      genre: 'Soul / RnB',
      tags: ['Corporate', 'Gala', 'Soul', 'Acoustic', 'Background set'],
      requirements: 'Clean, professional conduct and tasteful repertoire suitable for a corporate audience.',
      hostId: 'u_femi',
      hostName: 'Femi Okoro · Lagos Civic Hall',
      createdAt: iso(-6),
      updatedAt: iso(-6),
    },
    {
      id: 'g_acoustic_brunch',
      title: 'Acoustic Sunday Brunch',
      description: 'A boutique cafe is booking an acoustic act for Sunday brunch. Looking for a singer-songwriter or vocal/guitar duo to play a relaxed 3-hour set of originals and covers.',
      type: 'Restaurant / Cafe',
      venue: 'Island Café, Wuse 2',
      location: 'Abuja, Nigeria',
      date: iso(12),
      startTime: '11:00',
      endTime: '14:00',
      fee: { currency: 'NGN', amount: 75000 },
      capacity: 1,
      status: 'open',
      genre: 'Acoustic / Indie',
      tags: ['Brunch', 'Acoustic', 'Solo act', 'Cover mix'],
      requirements: 'Unplugged or light amplification only. Friendly, low-volume set.',
      hostId: 'u_chidi',
      hostName: 'Chidi Umeh · The Jazz House',
      createdAt: iso(-5),
      updatedAt: iso(-5),
    },
    {
      id: 'g_wedding_reception',
      title: 'Wedding Reception Band',
      description: 'A December wedding needs a highlife band for the reception. Looking for a 4-6 piece band able to play live for 4 hours, including first dance and highlife oldies.',
      type: 'Wedding',
      venue: 'Golden Dome Events Centre',
      location: 'Enugu, Nigeria',
      date: iso(95),
      startTime: '16:00',
      endTime: '21:00',
      fee: { currency: 'NGN', amount: 420000 },
      capacity: 1,
      status: 'open',
      genre: 'Highlife / Oldies',
      tags: ['Wedding', 'Band', 'Full production', 'Highlife'],
      requirements: 'Complete band (vocals, guitars, horns, drums). Transport for equipment is covered.',
      hostId: 'u_amara',
      hostName: 'Amara Kalu · PalmWaves Festival',
      createdAt: iso(-4),
      updatedAt: iso(-4),
    },
    {
      id: 'g_studio_session',
      title: 'Studio Session — Afro-Jazz EP',
      description: 'A producer is recording an Afro-jazz EP and needs a saxophonist and a vocalist for 2 studio days in Lagos. Flights/lodging covered for out-of-town artists.',
      type: 'Recording',
      venue: 'Third Ear Studio',
      location: 'Lagos, Nigeria',
      date: iso(30),
      startTime: '09:00',
      endTime: '18:00',
      fee: { currency: 'NGN', amount: 200000 },
      capacity: 2,
      status: 'open',
      genre: 'Afro-jazz / Fusion',
      tags: ['Studio', 'Session', 'EP', 'Afro-jazz'],
      requirements: 'Sight-reading skills, reliable timing, prepared to experiment. Send a sample of past studio work.',
      hostId: 'u_femi',
      hostName: 'Femi Okoro · Lagos Civic Hall',
      createdAt: iso(-3),
      updatedAt: iso(-3),
    },
    {
      id: 'g_praise_night',
      title: 'Church Praise Night — Guest Artist',
      description: 'A Lagos parish invites one guest vocalist and one keyboardist for a special praise night. We are looking for gospel musicians comfortable leading large congregational sessions.',
      type: 'Church / Gospel',
      venue: 'Remembrance Chapel',
      location: 'Lagos, Nigeria',
      date: iso(47),
      startTime: '17:00',
      endTime: '20:00',
      fee: { currency: 'NGN', amount: 65000 },
      capacity: 2,
      status: 'open',
      genre: 'Gospel',
      tags: ['Gospel', 'Guest artist', 'Choir', 'Praise night'],
      requirements: 'Rehearsal from 4:30pm on the day. Must have clean, uplifting repertoire.',
      hostId: 'u_chidi',
      hostName: 'Chidi Umeh · The Jazz House',
      createdAt: iso(-2),
      updatedAt: iso(-2),
    },
  ];

  const applications = [
    {
      id: 'a_001',
      gigId: 'g_sunset_jazz',
      musicianId: 'u_ayo',
      musicianName: 'Ayo Adeyemi',
      email: 'ayo@example.com',
      phone: '+234 800 000 0001',
      note: 'I can do a 75-minute live set and would love to bring a rhythm section. Happy to send a recent live clip.',
      status: 'pending',
      createdAt: iso(-2),
      updatedAt: iso(-2),
    },
    {
      id: 'a_002',
      gigId: 'g_year_end_gala',
      musicianId: 'u_grace',
      musicianName: 'Grace Eze',
      email: 'grace@example.com',
      phone: '+234 800 000 0002',
      note: 'Soul and RnB is my sweet spot. I have corporate event experience and can also MC the entertainment segment.',
      status: 'pending',
      createdAt: iso(-1),
      updatedAt: iso(-1),
    },
  ];

  return { users, gigs, applications };
}
